name = "octroi-example"
main = "src/index.ts"
compatibility_date = "2026-08-01"

# wrangler secret put OCT_ADDRESS   (or use a var for testnet)
[vars]
OCT_ADDRESS = "0x1111111111111111111111111111111111111111"
